/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 1-3D.com (https://sketchfab.com/1-3D.com)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/inkjet-printer-and-scanner-ecb6f40c66ff4307a3eadb67cabc83dc
Title: Inkjet printer and scanner
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Canon(props) {
  const { nodes, materials } = useGLTF('/models/inkjet_printer_and_scanner.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.semitrans}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['black-textured']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/inkjet_printer_and_scanner.glb')





