import avt1 from '../assets/avt1.jpg'
import avt3 from '../assets/avt3.jpg'
import avt4 from '../assets/avt4.jpg'
import printer1 from '../assets/printer1.jpg'
import printer2 from "../assets/printer2.jpg"
import printer3 from "../assets/printer3.jpg"


export const managers = [
  {
    name: 'Caitlyn',
    avatar: avt1,
  },
  {
    name: 'Jinx',
    avatar: avt1,
  },
  {
    name: 'Jayce',
    avatar: avt3,
  },
  {
    name: 'Viktor',
    avatar: avt4,
  }
]

export const printers = [
  {
    real_name: "Brother HL-L2366DW Wifi",
    location: "CS1",
    number: 1,
    status: "rest",
    img: printer1,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon LBP6030",
    location: "CS1",
    number: 2,
    status: "error",
    img: printer2,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon G3420",
    location: "CS1",
    number: 3,
    status: "rest",
    img: printer2,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "HP LaserJet M211d (9YF82A)",
    location: "CS1",
    number: 4,
    status: "rest",
    img: printer3,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon G3420",
    location: "CS1",
    number: 5,
    status: "rest",
    img: printer1,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "HP 108w (4ZB80A)",
    location: "CS1",
    number: 6,
    status: "rest",
    img: printer3,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon LBP6030",
    location: "CS1",
    number: 7,
    status: "rest",
    img: printer3,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Brother HL-L2366DW Wifi",
    location: "CS1",
    number: 8,
    status: "error",
    img: printer3,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },

  {
    real_name: "Brother DCP-B7640DW Wifi",
    location: "CS2",
    number: 1,
    status: "rest",
    img: printer2,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon LBP6030",
    location: "CS2",
    number: 2,
    status: "rest",
    img: printer1,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "HP 108w (4ZB80A)",
    location: "CS2",
    number: 3,
    status: "printing",
    img: printer2,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Brother HL-L2321D",
    location: "CS2",
    number: 4,
    status: "rest",
    img: printer3,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon LBP6030",
    location: "CS2",
    number: 5,
    status: "error",
    img: printer1,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon LBP6030",
    location: "CS2",
    number: 6,
    status: "rest",
    img: printer3,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon G3420",
    location: "CS2",
    number: 7,
    status: "printing",
    img: printer2,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
  {
    real_name: "Canon LBP6030",
    location: "CS2",
    number: 8,
    status: "printing",
    img: printer1,
    ink: "Canon 325",
    page_left: [180, 100],
    allowedPaperType: ["A3", "A4"],
    file_type: ["PDF", "DOCX", "PNG", "JPEG"],
    printed: 45,
  },
]


export const accounts = [
  {
    email: "anh.huynhanh@hcmut.edu.vn",
    name: "HUỲNH NGUYỄN NGỌC ANH",
    major: "Khoa học máy tính",
    studentID: "2252022",
    password: "Student123456",
    role: "student",
  },
  {
    email: "quan.hoangstephen180@hcmut.edu.vn",
    name: "HOÀNG MINH QUÂN",
    major: "Khoa học máy tính",
    studentID: "2212787",
    password: "Student123456",
    role: "student",
  },
  {
    email: "hung.huynhbk2022@hcmut.edu.vn",
    name: "HUỲNH GIA HƯNG",
    major: "Khoa học máy tính",
    studentID: "2252274",
    password: "Student123456",
    role: "student",
  },
  {
    email: "phuong.huynhlan@hcmut.edu.vn",
    name: "HUỲNH LAN PHƯƠNG",
    major: "Khoa học máy tính",
    studentID: "2252654",
    password: "Student123456",
    role: "student",
  },
  {
    email: "khoa.huynh314@hcmut.edu.vn",
    name: "HUỲNH NGỌC KHOA",
    major: "Khoa học máy tính",
    studentID: "2211591",
    password: "Student123456",
    role: "student",
  },
  {
    email: "spso@hcmut.edu.vn",
    name: "HCMUT SPSO",
    major: "Khoa hoc may tinh",
    studentID: "",
    password: "Spso123456",
    role: "spso",
  },
]

export const getUserRole = () => {
  const user = JSON.parse(localStorage.getItem("user"))
  return user ? user.role : null 
}